### ISSUE TITLE
feature: create a release pipeline

### ISSUE THREAD

**Issue by developer-guy** [afbjorklund/nerdctld#1]
Let's create a release pipeline based on GitHub Actions and start versioning the project.

**Comment by afbjorklund** [comment]
I can make a release (not sure about need for pipeline), but need to clear up some code

i.e. it needs to have parameters for socket and port, and whether to enable debugging

```go
func main() {
	nerdctlVersion()
	r := setupRouter()
	//r.Run(":2375")
	r.RunUnix("nerdctl.sock")
}
```

**Comment by afbjorklund** [comment]
Ther parameters are added, so it should be usable (hopefully). Should create a release.

**Comment by afbjorklund** [comment]
Made some manual releases, and added the targets for lint and artifacts to the Makefile

**Comment by afbjorklund** [comment]
* #4
